### ISSUE TITLE
Girlmore Girls

### ISSUE THREAD

**Issue by Agustoledo10** [pdepjm/2023-tp0-presentacion-VYEDID#3]
Hola vicki, una pregunta, de todos los pibes con los que salio rory  con cual te quedarias para ella y porque?? (kajkaj espero q vayas adelantada en la serie y no la estes empezando :p)

**Comment by victoriasolyedid** [comment]
Hola Agus! Ando por la temporada 5 de Gilmore girls y si te soy sincera la shipee a rory una banda tanto con dean como con jess , pero estos no hicieron más que decepcionarme. A este punto, creo que no me queda otra que quedarme con Lane para ella. Buena amiga, inteligente y aparte tiene una banda de rock
