### ISSUE TITLE
Canto

### ISSUE THREAD

**Issue by CeciC24** [pdepjm/2023-tp0-presentacion-VYEDID#4]
Buenas!!! Hace cuánto tiempo cantás Vicki? Qué géneros te gustan?

**Comment by victoriasolyedid** [comment]
Hola Ceci!! Creo que canto desde que tengo memoria jaja, pero arranqué con clases aproximadamente cuando tenía 8 años. Por más que me gustaría tener un gusto más amplio en géneros musicales,  prácticamente el único género que escucho es el pop, sobre todo el pop en inglés
