### ISSUE TITLE
Pasantía

### ISSUE THREAD

**Issue by MartuRoldan** [pdepjm/2023-tp0-presentacion-VYEDID#5]
Cómo conseguiste entrar en la pasantía? Te gustó arrancar a trabajar?

**Comment by victoriasolyedid** [comment]
Hola Martu! A fines del año pasado empecé a buscar puestos en sistemas por LinkedIn y me postulé directo por ese medio :) .Tuve una entrevista grupal para una pasantía en Mainframe pero no quedé para ese puesto, y a los dos días de rechazarme me dijieron que se había abierto uno nuevo para  "Access Management" y bueno acá estamos jajaja. La verdad que el trabajo me encanta, esta buenisimo poder conocer de cerca como se maneja una empresa y hacer algo relacionado a mi area, así que, aunque arranqué hace poquito, por ahora viene super bien!
