### ISSUE TITLE
Taylor

### ISSUE THREAD

**Issue by BritosAylen** [pdepjm/2023-tp0-presentacion-VYEDID#6]
Fuiste a ver a Taylor cuando vino? como la pasaste?

**Comment by victoriasolyedid** [comment]
Hola Aylu! Por ahora Taylor no vino nunca a Argentina, pero se rumorea que viene a fines de este año, asi que ando rezando para no tener que vender mi riñon o ningún otro organo para pagar la entrada 🙏
